apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gatekeeper-operator
  namespace: gatekeeper-system
spec:
  channel: stable
  name: gatekeeper-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
